language: go

go:
  - 1.8
  - 1.9
  - tip

cache:
  directories:
    - vendor

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov
  - go get -u github.com/Masterminds/glide
  - glide up -s -u

script:
  - make test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage-all.out -service=travis-ci
